backend:
  name: git-gateway
  branch: main

# Where Netlify CMS looks for uploads by default (not used with Cloudinary)
media_folder: "static/uploads"
# How those in‑repo uploads would be referenced (also not used here)
public_folder: "/uploads"

# ← Add this block to enable Cloudinary uploads
media_library:
  name: cloudinary
  config:
    cloud_name: designcenter
    api_key: 731759592841628
    default_transformations:
      - - fetch_format: auto
          quality: auto
    multiple: false
    # Removed the default upload_preset to avoid conflicts

collections:
  # BLOG (Markdown)
  - name: "posts"
    label: "Blog Posts"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "readTime", label: "Read Time (minutes)", widget: "number" }
      - name: "image"
        label: "Cover Image"
        widget: "object"
        fields:
          - { name: "url", label: "Image URL", widget: "image" }
          - { name: "alt", label: "Alt Text", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

  # PROJECTS (Transformations Page)
  - name: "projects"
    label: "Projects"
    folder: "src/data/projects"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { name: "slug",        label: "Slug",        widget: "string" }
      - { name: "title",       label: "Title",       widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - name: "images"
        label: "Images"
        widget: "list"
        fields:
          - { name: "url",   label: "Image URL",   widget: "image" }

  # TESTIMONIALS (How We Work Page)
  - name: "testimonials"
    label: "Testimonials"
    folder: "src/data/testimonials"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { name: "slug",   label: "Slug",   widget: "string" }
      - { name: "name",   label: "Name",   widget: "string" }
      - { name: "quote",  label: "Quote",  widget: "text" }
      - { name: "rating", label: "Rating", widget: "string" }

  # BRANDS (Collaborations Page)
  - name: "brands"
    label: "Brands"
    folder: "src/data/brands"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { name: "slug",        label: "Slug",        widget: "string" }
      - { name: "name",        label: "Name",        widget: "string" }
      - name: "logo"
        label: "Logo"
        widget: "image"
        media_library:
          config:
            folder: "Navbar_7/Logos_For_Navbar"
      - { name: "website",     label: "Website URL", widget: "string" }
      - { name: "description", label: "Description", widget: "text"   }

  # DESIGNERS (Designers Page)
  - name: "designers"
    label: "Designers"
    folder: "src/data/designers"
    create: true
    format: "json"
    fields:
      - { name: "name",        label: "Name",        widget: "string" }
      - { name: "description", label: "Description", widget: "text"   }
      - { name: "photo",       label: "Photo",       widget: "image"  }
      - { name: "website",     label: "Website",     widget: "string" }

  - name: "product-galleries"
    label: "Product Galleries"
    folder: "src/data/product-galleries"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - name: "room"
        label: "Room"
        widget: "select"
        options:
          - { label: "Kitchen", value: "Kitchen" }
          - { label: "Furniture", value: "Furniture" }
          - { label: "Lighting", value: "Light" }
          - { label: "Bath", value: "Bath" }
          - { label: "Outdoor", value: "Outdoor" }
          - { label: "Office", value: "Office" }
          - { label: "Closet", value: "Closet" }
      - name: "style"
        label: "Style"
        widget: "select"
        options:
          - { label: "Modern (Kitchen)", value: "Modern" }
          - { label: "Traditional (Kitchen)", value: "Traditional" }
          - { label: "Art Deco (Kitchen)", value: "Art_Deco" }
          - { label: "Living Room (Furniture)", value: "Living" }
          - { label: "Dining Room (Furniture)", value: "Dining" }
          - { label: "Bedroom (Furniture)", value: "Bedroom" }
          - { label: "None", value: "" }
        required: false
      - name: "image"
        label: "Image"
        widget: "image"
        hint: "Select an image to auto-fill title"
      - { name: "title", label: "Title", widget: "string" }